# Generated by Django 5.2 on 2025-08-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deleted',
            field=models.BooleanField(default=0, verbose_name='削除'),
        ),
    ]
